# Generated by Django 5.2.4 on 2025-08-07 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('status', models.CharField(choices=[('판매중', '판매중'), ('예약중', '예약중'), ('판매완료', '판매완료')], default='판매중', max_length=10, verbose_name='거래 상태')),
                ('type', models.CharField(choices=[('sell', '판매'), ('buy', '구매')], max_length=10, verbose_name='게시글 유형')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='지역 필터용')),
                ('method', models.CharField(blank=True, choices=[('직거래', '직거래'), ('택배', '택배')], max_length=20, verbose_name='거래 방식')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='카테고리')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='posts.post', verbose_name='연결된 게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='등록한 사용자')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='상품')),
            ],
        ),
    ]
