# Generated by Django 5.2.4 on 2025-08-08 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="카테고리"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("판매중", "판매중"),
                            ("예약중", "예약중"),
                            ("판매완료", "판매완료"),
                        ],
                        default="판매중",
                        max_length=10,
                        verbose_name="거래 상태",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("sell", "판매"), ("buy", "구매")],
                        max_length=10,
                        verbose_name="게시글 유형",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="지역 필터용"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("직거래", "직거래"), ("택배", "택배")],
                        max_length=20,
                        verbose_name="거래 방식",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록한 사용자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="이미지 URL")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="좋아요 누른 시각"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_likes",
                        to="products.product",
                        verbose_name="좋아요 상품",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="좋아요 누른 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 좋아요",
                "verbose_name_plural": "상품 좋아요 목록",
                "unique_together": {("product", "user")},
            },
        ),
    ]
