# Generated by Django 5.2.5 on 2025-08-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettypedetail',
            name='pet_type',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
        migrations.DeleteModel(
            name='PetTypeDetail',
        ),
    ]
