# Generated by Django 5.2.5 on 2025-08-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_alter_chatroom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
