# Generated by Django 5.2.5 on 2025-08-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_state_city"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.city",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.state",
            ),
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
