name: 11 Django Mini CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Packages & Libraries
        run: |
          uv sync

      - name: Run ruff
        run: |
          echo "Starting ruff"
          uv run ruff format
          uv run ruff check --fix
          echo "OK"